eureka:
  instance:
   hostname: localhost
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 zipkin:
  baseUrl: http://localhost:9411
 cloud:
  config:
   override-system-properties: false
